### ISSUE TITLE
Set Up Shortcut/Taskbar Support

### ISSUE THREAD

**Issue by ghost** [DryestDuke/Dungeons-and-Dragons-Utility-Tool#13]
Related to #2.

"Shift+right click" on taskbar makes setting it up easy, but ideally it wouldn't have to be "hacked in".

**Comment by DryestDuke** [comment]
Likely through creating a .exe

**Comment by DryestDuke** [comment]
For JAVA files you just have to hack this in - I don't want to risk anything, so I'm giving up on this (especially because it's really just QoL).
