### ISSUE TITLE
Allows Saving of NPC's, via GUI

### ISSUE THREAD

**Issue by ghost** [DryestDuke/Dungeons-and-Dragons-Utility-Tool#19]
Ideally, click a button to save an NPC to a save file. Have a screen on the GUI with a list of all saved NPC's, to be consulted whenever desired.

#2.

Per #25, have an option for Saving to File and Saving for Session. "Saving to File" allows loading of the NPC across all sessions, while "Saving for Session" keeps them in the screen on the GUI for the entire run time of the program, but once it is exited the data is lost (obviously).

**Comment by DryestDuke** [comment]
Also, don't forget #20.

Also, it would be nice to add a "header" to each saved NPC - i.e.; the information on that NPC is saved under a header consisting of the name + myNote, wherein myNote is a note to identify the NPC (e.g.; myNote = "this kid runs the  convenience store down the street").

**Comment by DryestDuke** [comment]
Also, look at other NPC-related issues before implementing this - although this could be done first, might be best to do last.
